config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'events#index'
  
  resources :participants
  resources :events
  resources :users
#  resources :users, only: [:new, :create, :show, :destroy, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :users
  belongs_to :user, optional: true
  
  has_many :participants, dependent: :destroy
  has_many :participant_users, through: :participants, source: :user

  validates :title,  presence: true
  validates :content,  presence: true
  validates :place,  presence: true
  validates :event_at,  presence: true
  validates :eventend_at,  presence: true

  mount_uploader :image, ImageUploader

end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
#  belongs_to :participant_id ,class_name: 'user' ,foreign_key: 'user_id'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  belongs_to :event, optional: true

  has_many :participants, dependent: :destroy
  has_many :participant_events, through: :participants, source: :event

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email_address, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save {email_address.downcase! }
  has_secure_password
#  validates :password, presence: true, length: { minimum: 6 }

  mount_uploader :icon, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :edit, :show]

  # GET /events
  # GET /events.json
  def index
#    @events = Event.all
    @q = Event.ransack(params[:q])
    @events = @q.result(distinct: true).order("event_at ASC")
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.all
    @participant = current_user.participants.find_by(event_id: @event.id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'イベントを登録しました' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'イベントを更新しました' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'イベントを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :image, :organizer_id, :event_at, :place, :eventend_at, :user_id)
    end

    def require_login
    unless logged_in?
      flash[:error] = "ログインが必要です"
      redirect_to new_session_url # halts request cycle
    end
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def create
    participant = current_user.participants.create(event_id: params[:event_id])
    redirect_to events_url, notice: "登録しました"
  end

  def destroy
    participant = current_user.participants.find_by(event_id: params[:event_id]).destroy
    redirect_to events_url, notice: "解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
  user = User.find_by(email_address: params[:session][:email_address].downcase)
    if user && user.authenticate(params[:session][:password_digest])
      session[:user_id] = user.id
      redirect_to events_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'こんにちは！ユーザ登録ありがとうございます' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
#      @user = User.find(params[:id])
      if @user.update(user_params)
        format.html { redirect_to @user, notice: '画像を更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '退会しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email_address, :password, :icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fdate arg
    arg.present? ? Date.parse(arg).strftime("%Y/%m/%d") : ""
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
    
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
    
  def logged_in?
    !current_user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :イベント名 %>
    <%= form.text_field :title, id: :event_title, size:50 %>
  </div>

  <div class="field">
    <%= form.label :開催日時 %>
      <%= form.datetime_field :event_at %>
  </div>

  <div class="field">
    <%= form.label :終了日時 %>
      <%= form.datetime_field :eventend_at %>
  </div>

  <div class="field">
    <%= form.label :場所 %>
    <%= form.text_field :place, id: :event_place, 
    placeholder:"東京都港区ｘｘx-xx-xx　○○ビルxx階 ○○セミナールーム", size:60 %>
  </div>

  <div class="field">
    <%= form.label :内容 %>
    <%= form.text_area :content, id: :event_content, 
    placeholder:"イベントの概要、詳細（費用、タイムテーブル等）フリーで記載ください", cols:70, rows:10 %>
  </div>

  <div class="field">
    <%= form.label :イベントイメージ画像 %>
    <%= form.file_field :image, id: :event_image %>
    <%= form.hidden_field :image_cache %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.1.erb
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>日時</th>
      <th>場所</th>
      <th>概要</th>
      <th>画像</th>
      <th>Organizer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>  
        <td><%= event.event_at %></td>
      </tr>
      <tr>
        <td><h1><%= event.title %></h1></td>
      </tr>
      <tr>  
        <td><%= event.place %></td>
        <td><%= event.content %></td>
        <td><%= image_tag event.image, :size =>'50x50' %></td>
        <td><%= event.organizer_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/index.html.2.erb
<h1>気になるイベントを見つけよう</h1><br>

<table>
  <tbody>
    <% @events.each do |event| %>
      <tr>  
        <td><%= event.event_at.to_s(:date) %></td>
      </tr>
      <tr>  
        <td><%= event.event_at.to_s(:time) %></td>
      </tr>
      <tr>
        <td><h1><%= link_to event.title, event %></h1></td>
      </tr>
      <tr>  
        <td><%= event.place %></td>
      </tr>
      <tr>  
        <td><%= event.content %></td>
      </tr>
      <tr>  
        <td><%= image_tag event.image, :size =>'50x50' %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/index.html.erb
    <div class="jumbotron"  style="background:linear-gradient(-135deg, #34BDE9 0%, #4660D0 100%); background-size:cover;">
      <div class="container">
        <h3 class="head">気になるイベントを見つけよう！</h3><br>

        <%= search_form_for @q do |f| %>
        <div class="row">
          <div class="col-lg-3">
          </div>
          <div class="col-lg-6">
            <div class="input-group">
              <%= f.search_field :title_or_content_or_place_cont, 
              placeholder:"例)　東京、ライブ、Ruby　等", class: "form-control" %>
              <span class="input-group-btn">
                <input class="btn btn-info" type="submit" value="検索">
              </span>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>


<div class="row">
<div class="col-lg-9">
<table>
  <tbody>
    <% @events.each do |event| %>
    <% if event.event_at >= DateTime.now.to_time %>
    <table class="list-group-item">
      <tr>
        <td><%= event.event_at.to_s(:date) %></td>
      </tr>
      <tr>
        <td><%= event.event_at.to_s(:time) %>
        <% @event = Event.find(event.id) %>
        <%= image_tag @event.user.icon, :width => '20', :height => '20' %>
        <%= @event.user.name %></td>
      </tr>
      <tr>
        <td><h1><%= link_to event.title, event %></h1></td>
      </tr>
      <tr>  
        <td><%= event.place %></td>
      </tr>
    </table>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
<div class="col-lg-3">
<h3>日付(期間)で探す</h3>
  <%= search_form_for @q do |f| %>
    <p><%= f.label :検索開始日 %>
      <%= f.date_field :event_at_gteq, class: "date",
      placeholder: "yyyy/mm/dd", value: fdate(params[:q] && params[:q][:event_at_gteq]) %></p>
    <p><%= f.label :検索終了日 %>
      <%= f.date_field :event_at_lteq_end_of_day, class: "date", 
      placeholder: "yyyy/mm/dd", value: fdate(params[:q] && params[:q][:event_at_lteq_end_of_day]) %></p>
        <input class="btn btn-info" type="submit" value="検索">
  <% end %>
</div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.1.erb
<p>
  <strong>Title:</strong>
  <h1><%= @event.title %></h1>
</p>

<p>
  <%= image_tag 'clock.png', :size =>'15x15' %>
  <%= @event.event_at.to_s(:event_at) %>
</p>

<p>
  <%= image_tag 'locater.jpg', :size =>'15x15' %>
  <%= @event.place %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @event.image %>
</p>

<p>
  <strong>詳細:</strong>
  <%= @event.content %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @event.organizer_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
  <div class="panel panel-default">
    <div class="panel-heading">
  <h3><%= image_tag @event.user.icon, :width => '40', :height => '40' %>
    <%= @event.user.name %></h3>
    </div>

    <div class="jumbotron"  style="background:url(<%= @event.image %>)center no-repeat; background-size:cover;">
      <div class="container">
        <h1>　</h1>
        <h1>　</h1>
      </div>
    </div>
    
<p>
  <h2 class="he2"><%= @event.title %></h2>
</p>

<p class="line">
  <%= image_tag 'clock.png', :size =>'15x15' %>　
  <%= @event.event_at.to_s(:event_at) %> ～
  <%= @event.eventend_at.to_s(:event_at) %>
</p>

<p class="line">
  <%= image_tag 'locater.jpg', :size =>'15x15' %>　
  <%= @event.place %>
</p>

<p class="line">
  <%= image_tag 'peple.png', :size =>'15x15' %>　
    <% @event.participant_users.reverse_each do |event| %>
        <%= image_tag event.icon, :width => '20', :height => '20' %>
        <%= event.name %>　
    <% end %>
</p>

<p class="line">
<% unless @event.user_id == current_user.id %>
  <% if @participant.present? %>
    <%= link_to '申し込みを取り消す', participant_path(event_id: @event.id), method: :delete, class: 'btn btn-danger btn-lg' %>
  <% else %>
    <%= link_to '申し込む', participants_path(event_id: @event.id), method: :post, class: 'btn btn-success btn-lg' %>
  <% end %>
<% end %>
</p>

<p class="line">
  <%= simple_format(@event.content, :class => "content") %>
</p>

<p></p>
<p class="line">
<% if @event.user_id == current_user.id %>
<%= link_to '編集', edit_event_path(@event), class: 'btn btn-info btn-lg' %> |
<%= link_to '削除', @event, method: :delete, class: 'btn btn-danger btn-lg', data: { confirm: 'Are you sure?' } %>
<% end %>
</p>
<p></p>
<p class="line">
<%= link_to '戻る', events_path %>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventma</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-default">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">メニュー</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">EVENTAMA</a>
  　     <%= image_tag 'eventma.jpg', :size =>'54x54' %>
      </div>
 
      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
          <li><%= link_to '新規イベント登録', new_event_path %></li>
          <li><%= link_to "イベント一覧画面", events_path %></li>
          <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>

        <% else %>
          <li><%= link_to "新規ユーザ登録", new_user_path %></li>
          <li><%= link_to "ＥＶＥＮＴＭＡログイン", new_session_path %></li>
        <% end %>
        </ul>
      </div>
    </nav>
    
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>




    <%= yield %>
  </body>
</html>

app/views/participants/_form.html.erb
<%= form_with(model: participant, local: true) do |form| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id, id: :participant_event_id %>
  </div>

  <div class="field">
    <%= form.label :participant_id %>
    <%= form.number_field :participant_id, id: :participant_participant_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Participant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.event_id %></td>
        <td><%= participant.participant_id %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @participant.event_id %>
</p>

<p>
  <strong>Participant:</strong>
  <%= @participant.participant_id %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :氏名 %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :メールアドレス %>
    <%= form.text_field :email_address, id: :user_email_address %>
  </div>

  <div class="field">
    <%= form.label :パスワード %>
    <%= form.text_field :password, id: :user_password_digest %>
  </div>

  <div class="field">
    <%= form.label :パスワード確認 %>
    <%= form.text_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.file_field :icon, id: :user_icon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.1.erb
<h1>Editing User</h1>

<% if false %><%= render 'form', user: @user %><% end %> 

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user.email_address %>
</p>

<!--  <section>
  <span> -->
    <%= image_tag @user.icon %>
<!--  </span><br>
  <span class="col-xs-5 col-md-5"></span>
  <span class="col-xs-7 col-md-7"> -->
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
<!--  </span>
  </section> -->

  <%= form.submit %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
  <h1>Editing User</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
  <%= form.label :name %>
  <%= form.text_field :name, id: :user_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user.email_address %>
</p>

  <%= image_tag @user.icon %>
  <%= form.file_field :icon %>
  <%= form.hidden_field :icon_cache %>

  <%= form.submit %>

<p>
<%= link_to 'Back', user_path %>
</p>

<% end %>

app/views/users/index.html.1.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email address</th>
      <th>Password digest</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email_address %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.icon %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/index.html.erb
<%= link_to '新規ユーザ登録', new_user_path %>
<br>
<%= link_to 'ＥＶＥＮＴＭＡ ログイン', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', events_path %>

app/views/users/show.html.1.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user.email_address %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Icon:</strong>
  <%= image_tag @user.icon %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', new_user_path %>

app/views/users/show.html.erb
<div class="row">
<div class="col-lg-5">
<p>
  <strong>お名前:</strong>
  <%= @user.name %>さん
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @user.email_address %>
</p>

<p>
  <strong>画像:</strong>
</p>
  <%= image_tag @user.icon %>
<br>
<%= link_to '編集', edit_user_path(@user) %> |
<%= link_to '戻る', events_path %>
<p>
<%= link_to '退会する', @user, method: :delete, data: { confirm: '本当に退会しますか？' }, class: 'btn btn-danger'  %>
</p>
</div>
<div class="col-lg-7">
    <h3>参加イベント一覧</h3>
    <% @user.participant_events.reverse_each do |user| %>
    <% if user.event_at >= DateTime.now.to_time %>
    <table class="list-group-item">
      <div class="col-xs-12 col-md-12 blog-panel2">
      <tr>  
        <td><%= user.event_at.to_s(:date) %></td>
      </tr>
      <tr>
        <td><%= user.event_at.to_s(:time) %></td>
      </tr>
      <tr>
        <td><h1><%= user.title %></h1></td>
      </tr>
      <tr>  
        <td><%= user.place %></td>
      </tr>
      </div>
    </table>
    <% end %>
    <% end %>
</div>